- name: cart
  hosts: cart
  become: yes
  tasks: 
  - name: disbale new nodejs and enable new nodejs
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name:  create adduser roboshop
    ansible.builtin.user:
      name: roboshop

  - name: create directoty file
    ansible.builtin.file:
      path: /app   
      state: directory

  - name: download the file in the directory
    ansible.builtin.get_url:
      url: /tmp/cart.zip https://roboshop-builds.s3.amazonaws.com/cart.zip
      dest: /tmp

  - name: extract catalogue application
    ansible.builtin.unarchive:
      src: /tmp/cart.zip
      dest: /app
      remote_src: yes   

  - name: Install dependencies
    ansible.builtin.command: npm install
    args:
      chdir: /app 

  - name: Copy cart service
    ansible.builtin.copy:
      src: cart.service
      dest: /etc/systemd/system/cart.service   

  - name: deamon realod and start
    ansible.builtin.systemd_service:
      daemon_reload: true 

  - name: start and enable cart
    ansible.builtin.service:
      name: cart
      state: restarted             
          


