- name: mongodb
  hosts: mongodb
  become: yes
  tasks: 
  - name: copy mongodb
    ansible.builtin.copy:
      src: mongodb.repo
      des: /etc/yum.repos.d/mongodb.repo

  -  name: install mongodb
     ansible.builtin.package:
       name: mongodb-org
       state: present

  -  name: start and enable momgodb
     ansible.builtin.service:
       name: mongod
       state: started
       enable: yes  

  - name: allow remote conncections
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: start and enable mongodb
    ansible.builtin.service:
      name: mongod
      state: restarted          