- name: user
  host: user
  become: yes
  tasks:
  - name: diable old nodejs and enable new nodejs]
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name:  create adduser roboshop
    ansible.builtin.user:
      name: roboshop

  - name: creating a app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: download the user file in app directory
    ansible.builtin.get_url:
      url: /tmp/user.zip https://roboshop-builds.s3.amazonaws.com/user.zip 
      dest: /tmp  

  - name: extract user application 
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /tmp
      remote_src: yes

  - name: Install dependencies
    ansible.builtin.command: npm install
    args:
      chdir: /app 

  - name: Copy cart service
    ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service    

  - name: deamon realod and start
    ansible.builtin.systemd_service:
      daemon_reload: true 

  - name: Copy mongodb repo
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongodb.repo

  - name: Install mongodb client
    ansible.builtin.package:
      name: mongodb-org-shell
      state: present 

  - name: get the categories count
    ansible.builtin.command:  mongo --host mongodb.praveenapp.online --quiet --eval 'db = db.getSiblingDB("user"); db.products.count()'
    register: product_count  

  - name: load catalogue data
    ansible.builtin.command: mongo --host mongodb.praveenapp.online < /app/schema/user.js
    when: product_count.stdout == 0 

  - name: start and enable cart
    ansible.builtin.service:
      name: user
      state: restarted               
      enabled: yes

               